# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13j24J3IKGqEcEpcTuGP4gKj6XoiCXCah
"""

from flask import Flask, request
import mysql.connector

app = Flask(__name__)

db = mysql.connector.connect(
    host="localhost",
    user="tu_usuario",
    password="tu_contraseña",
    database="reto_db"
)
cursor = db.cursor()

@app.route('/data', methods=['POST'])
def recibir_datos():
    temp = request.form.get('temperatura')
    hum = request.form.get('humedad')
    sql = "INSERT INTO mediciones (temperatura, humedad) VALUES (%s, %s)"
    cursor.execute(sql, (temp, hum))
    db.commit()
    return "OK", 200

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000)